using System;
using System.Collections.Generic;
using System.Reflection;
using System.Text;
using Core.Bookings;
using Core.Common;
using Core.Locations;
using Core.Organizations;
using Core.Pets;
using Microsoft.EntityFrameworkCore;

namespace Infrastructure.Data
{
    public class ApplicationContext : DbContext
    {
        public ApplicationContext(DbContextOptions<ApplicationContext> options) : base(options)
        {
        }

        public DbSet<Organization> Organizations { get; set; }
        public DbSet<Location> Locations { get; set; }
        public DbSet<Pet> Pets { get; set; }
        public DbSet<Booking> Bookings { get; set; }
        public DbSet<BookingDetails> BookingDetails { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly());

            AutoGeneratedProperties<Organization>(modelBuilder);
            AutoGeneratedProperties<Location>(modelBuilder);
            AutoGeneratedProperties<Pet>(modelBuilder);
            AutoGeneratedProperties<Booking>(modelBuilder);
            AutoGeneratedProperties<BookingDetails>(modelBuilder);
        }

        private void AutoGeneratedProperties<T>(ModelBuilder mb) where T : BaseEntity
        {
            mb.Entity<T>()
                .Property(entity => entity.Id)
                .ValueGeneratedOnAdd();
            mb.Entity<T>()
                .Property(entity => entity.CreatedUtc)
                .ValueGeneratedOnAdd();
            mb.Entity<T>()
                .Property(entity => entity.LastModifiedUtc)
                .ValueGeneratedOnUpdate();
        }
    }
}
